### ISSUE TITLE
Add Subscribe Pro channel code to Braintree card payments

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/sub-demandware#13]
* Subscribe Pro's BN code is `SubscribePro_BT`.
* The Subscribe Pro SFCC Cartridge should override the Braintree Cartridge
* We need to pass this value in the `channel` field: https://developer.paypal.com/braintree/docs/reference/request/transaction/sale/php#channel
* Braintree SFCC cartridge is here: https://github.com/SalesforceCommerceCloud/link_braintree

**Comment by iivanovRaccoonLLC** [comment]
Hi @garthbrantley 
Here is a PR - https://github.com/subscribepro/sub-demandware/pull/14
branch for it were created from this branch - bugfix/fix-checkout-sfra, and destination branch is also bugfix/fix-checkout-sfra

Thanks, Ivan
