### ISSUE TITLE
Multi-location Stock-Level / Inventory Feed SFCC > SP

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/sub-demandware#22]
Requirements are still being developed.

**Blocked**: The necessary APIs must be added to Subscribe Pro Commerce Platform as a pre-requisite to work on this issue.

## Subscribe Pro API Rate Limit

We have a rate limit on our APIs of 600 calls per minute from a single IP address - https://docs.subscribepro.com/technical/rest-api/#api-rate-limit

## Requirements

- One-way inventory / stock level feed from SFCC to Subscribe Pro
- Job will need to create new locations in Subscribe Pro if they don't exist
- Subscribe Pro API will provide operations for:
  - GET all locations
  - POST create new location

### Multi-Warehouse Inventory Integration
Develop additions to the Subscribe Pro Commerce Cloud Cartridge which provide the ability to sync inventory from Commerce Cloud to Subscribe Pro.
- Inventory feed runs as a background job on Commerce Cloud
- Configurable job schedule on Commerce Cloud (For example daily, hourly, every 30 minutes)
- Features integrated with the existing OOTB Commerce Cloud Cartridge (https://github.com/subscribepro/sub-demandware)
- Background job consumes Subscribe Pro APIs and makes API calls from Commerce Cloud to Subscribe Pro to sync products, product attributes and stock levels on each job run
- Integration supports multiple Commerce Cloud Inventory Lists

### Multi-Warehouse Inventory Support - Subscription Platform / APIs
Develop additional APIs and extensions to existing API endpoints to allow Subscribe Pro to ingest and make available multiple inventory stock levels, per warehouse (location).
- API endpoints will be made available as part of Subscribe Pro’s v2 and / or v3 public APIs. (https://docs.subscribepro.com/technical/rest-api/)
- Allow viewing / editing inventory stock levels for all warehouses (locations) in Subscribe Pro Merchant App for each product

**Comment by garthbrantley** [comment]
We expected APIs to be completed by 5/10 and available on 5/11.

**Comment by chrismshea** [comment]
I tested out the inventory feed and something happened that I don't understand.
I ran the feed out of the box so it synced the inventory list for inventory_m as expected.  I then added inventory to an item for another inventory list, and only synced that list by adding inventory_m_store_german_store to the job config, and it overwrote the inventory record previously created.

https://www.loom.com/share/b6a25a9723724b1ba1829fba962f88d8?sid=9ff77aa6-868d-413d-8765-3c87df3c8621

**Comment by chrismshea** [comment]
@okozllov I'm not seeing the addresses in the inventory locations.  I think this information would come from `Merchant Tools > Online Marketing > Stores`

Each store then is assigned an inventory list from a dropdown.

![SFCC_Stores-Inventory_List](https://github.com/subscribepro/sub-demandware/assets/1232258/a7f0b1ce-ca3c-4ef3-b2b3-cf24d6b44851)

**Comment by chrismshea** [comment]
Testing this, and

1. Email is not synced
2. What is the difference in use of the inventory list dropdown selector, and the text field on the inventory tab of the store?  In the sandbox seems like 1 or the other are used.
