### ISSUE TITLE
Eliminate Wallet Assist Widget

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/sub-demandware#23]
Eliminate the wallet widget. Instead, implement the same business logic via API calls from the back-end of SFCC.

This was the conversation between @iivanovRaccoonLLC and @garthbrantley 

> Ivan
> Hi Garth.
> What about if we change architecture of a cartridge?
> to be honest - I do not think we we need to use widgets for address and for payment - as it can be done via api calls.
> and better to utilise hooks approach for call to sub pro?

> Garth
> Ok, that makes sense

**Comment by chrismshea** [comment]
Experiencing an issue where credit cards are not saved to SP when until the 4th credit card is added to SFCC.

Have a look here https://subscribeproinc.sharefile.com/d-se73b2eb7421746adb456e67be69dd086
[20:18](https://subscribepro.slack.com/archives/D05BFLJ6CCT/p1688062732653339)
There’s a big video.  I’m out of loom space
[20:19](https://subscribepro.slack.com/archives/D05BFLJ6CCT/p1688062762819799)
Seems to work as expected after 3 profiles already exist :shrug::skin-tone-2:
