### ISSUE TITLE
Scripts or jobs that can be run to sync customer data to SP.

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/sub-demandware#33]
When doing Migrations we need to create the customers, addresses, payment profiles in subscribe pro.  Each of these get an entity id from SP that needs to get posted back to SFCC.

Issues when generated ID's not mapped back to SFCC Entities:
`subproCustomerID` - Issue: Customer cannot see there created subscriptions
`subproAddressID` - Issue:
`subproPaymentProfileID` - Issue: If customer creates a new subscription with saved payment Instrument a 409 will be generated due to the duplicate payment token.

I would like a way to run a script/job to be able to filter and create customers/addresses/payment instruments from SFCC to SP, and write the entity IDs back to SFCC.

This negates the step to have to come back, and update these entities in SFCC with a CSV, etc.

**Comment by chrismshea** [comment]
Hi @okozllov,
For this issue I need a way to filter/create customers on SP from SFCC.  Those which do not already have a SP Customer Id.  Let me know if you have any questions.  This is different from other tasks for keeping profiles in sync.

**Comment by okozllov** [comment]
Hi @chrismshea 
As I understood You would like to add one more button to choose between synchronizing already existing customers on the SP side (only customers who have subproCustomerID on the SFCC side) and all registered customers on the site (customers with subproCustomerID and without it). Have I understood correctly?
Or we can add a filter to synchronize separately customers with subproCustomerID  and customers without subproCustomerID

**Comment by chrismshea** [comment]
That's pretty much it, would like a way to sync those with SP Customer ID, and those that do not have a customer id.  I'm also curious if it is possible to have other filters as options on which customers to sync.  like "created since" date or something.  Are there any standard customer filters available?

**Comment by okozllov** [comment]
You can find all available filters on the Merchant Tools > Customers > Customers Advanced tab
Also includes Extended Attributes
![image](https://github.com/subscribepro/sub-demandware/assets/119881336/3afb28bb-ab82-47a0-b694-e38f38b6a1a3)

**Comment by okozllov** [comment]
Hi @chrismshea 
I recorded a short video how it can be implemented. Please let me know if you don't manage to open it

https://github.com/subscribepro/sub-demandware/assets/119881336/f25ed74b-b82c-4dde-ade3-022cd1d8c8db

**Comment by chrismshea** [comment]
Hey @okozllov that looks perfect for now!

**Comment by okozllov** [comment]
Hi @chrismshea 
PR for the filters: https://github.com/subscribepro/sub-demandware/pull/64
