### ISSUE TITLE
When payment profiles are added from the My Credit Cards an empty address is created.

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/sub-demandware#9]
Requirements:
- When triggering the Subscribe Pro WalletAssist widget to make API call to SP to create new credit card profile - 
  - Customer's SFCC default address should be passed in the `billingAddress` fields to Subscribe Pro widget
  - See: https://docs.subscribepro.com/technical/hosted-widgets/wallet-assist-widget/implementing/

Code to trigger the Subscribe Pro WalletAssist widget new card is here:
- https://github.com/subscribepro/sub-demandware/blob/main/cartridges/int_subscribe_pro_sfra/cartridge/templates/default/account/payment/payment.isml#L64

**Comment by garthbrantley** [comment]
Per discussion with @iivanovRaccoonLLC -
* If "default address" exists for customer - send it with the new profile data in the `billingAddress` field
* If customer does not have a "default address",
  * Then - Popup will prompt customer to enter a default address,
  * New "default address" will be saved
  * New "default address" will also be sent to Subscribe Pro with payment profile

**Comment by garthbrantley** [comment]
@iivanovRaccoonLLC Please move this business logic to API calls on the back-end of SFCC. Remove the address book widget.

**Comment by garthbrantley** [comment]
Implement this - conversation between @iivanovRaccoonLLC and @garthbrantley 

> Ivan
> Hi Garth.
> What about if we change architecture of a cartridge?
> to be honest - I do not think we we need to use widgets for address and for payment - as it can be done via api calls.
> and better to utilise hooks approach for call to sub pro?

> Garth
> Ok, that makes sense
